CREATE TABLE PAYMENT(
    PAYMENT_ID IDENTITY PRIMARY KEY,
    STATE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(8,2) NOT NULL
);

CREATE TABLE PRE_AUTH(
    PRE_AUTH_ID IDENTITY PRIMARY KEY,
    STATE VARCHAR(20) NOT NULL,
    PAYMENT_ID BIGINT NOT NULL,

    FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE AUTH(
    AUTH_ID IDENTITY PRIMARY KEY,
    STATE VARCHAR(20) NOT NULL,
    PAYMENT_ID BIGINT NOT NULL,

    FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);